env: cdt
spring:
  artemis:
    cluster: sq1125
    user: relaystream-selfservice-consumer
    password: 
  datasource:
    url: jdbc:postgresql://relaystream-nonprod.postgres.database.azure.com:5432/selfservice_cdt?sslmode=require
    username: selfservice_cdt
    password: 
    hikari:
      schema: selfservice_cdt
